version: '3.8'

services:
  portal-ui:
    image: node:18.1-alpine
    user: node
    working_dir: /home/node/clin-portal-ui
    entrypoint: tail -f /dev/null
    ports:
      - ${PORTAL_UI_PORT}:${PORTAL_UI_PORT}
    volumes:
      - ../clin-portal-ui:/home/node/clin-portal-ui
